### ISSUE TITLE
JSON property matching from request body in script

### ISSUE THREAD

**Issue by PauulM** [outofcoffee/imposter#66]
Hi, is there a way to get a specific property of a JSON that is being sent in a request **in a groovy script**? `context.request.body` returns a plain string and I'm unable to use groovy.json.JsonSlurper to parse as I'm getting `unable to resolve class groovy.json.JsonSlurper` when I try to import it.

**Comment by outofcoffee** [comment]
Added documentation for this: https://docs.imposter.sh/groovy_tips/

**Comment by hilsonp** [comment]
> @PauulM The easiest solution I've found is to capture the content in a store. When you access it it's been already parsed so you can do what you want with it
> 
> ```
> # imposter-config.yaml
> plugin: rest
> 
> resources:
> - path: /
>   method: POST
>      capture:
>        content:
>          jsonPath: $
>          store: request
>   response:
>     staticData: "${request.content:$.hello}"
>     template: true
> ```
> 
> but if you really want to use a script you can also do
> 
> ```
> # imposter-config.yaml
> plugin: rest
> 
> resources:
> - path: /
>   method: POST
>      capture:
>        content:
>          jsonPath: $
>          store: request
>   response:
>     scriptFile: json-parse.groovy
> ```
> 
> ```
> // json-parse.groovy
> def content = stores.open('request').load('content')
> respond().withData(content.hello)
> ```

Thank you for the tip but how do you cope with concurrent calls ?
Even though you would find a unique id, the store would then grow and never be cleaned until restart.

**Comment by cscetbon** [comment]
@hilsonp I didn't even think of it cause I only use it in integration tests and they're all different ...

**Comment by outofcoffee** [comment]
Hi both, the `request` store only exists for the duration of the associated request; i.e. there’s one per request. Once the request is completed, its request store is removed, so there’s no accumulation of data over time. This is because the behaviour of the request store is special; other stores retain their data until items are removed.

Internally, each request’s store is actually an ephemeral store, named something like `request_<request ID>`. Imposter maps requests to the ‘request’ store from your scripts or config to the specific one for the current request, transparently. This means concurrent requests have their own request store and don’t overlap.
