### ISSUE TITLE
multiple rules for same path not working

### ISSUE THREAD

**Issue by cscetbon** [outofcoffee/imposter#67]
I'm trying to use this feature that was introduced in 2.9.0, however it doesn't work. Here is the configuration I use
```
plugin: rest

resources:
- method: GET
  path: /example
  requestBody:
    jsonPath: $.foo
    value: bar
  response:
    statusCode: 500

- method: GET
  path: /example
  requestBody:
    jsonPath: $.baz
    value: 99
  response:
    statusCode: 302
```

But when trying to query the same path with a different body I would expect the 1st rule, the 2nd rule, or none of them to match. However I see 3 issues:
- the value for baz which is 99 matches only if use string "99" in the body but not integer 99
- imposter returns the response of the 1st rule instead of the 2nd rule when it matches the 2nd (Using default HTTP 500 response behaviour)
- imposter returns the response of the 1st rule when there is nothing that matches (Using default HTTP 500 response behaviour)

Here are my different tests

Query with baz having value "99" (string) which should not match any rule
```
/ # curl -v -d '{"baz": "99"}' -X GET http://localhost:8888/example
*   Trying 127.0.0.1:8888...
* Connected to localhost (127.0.0.1) port 8888 (#0)
> GET /example HTTP/1.1
> Host: localhost:8888
> User-Agent: curl/7.79.1
> Accept: */*
> Content-Length: 13
> Content-Type: application/x-www-form-urlencoded
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< X-Imposter-Request: 2b60c533-ac0e-4e7d-9693-522fe17ff8c7
< Server: imposter
< content-length: 0
<
* Connection #0 to host localhost left intact
```

imposter side
```
22:04:30 DEBUG i.g.i.s.ResourceServiceImpl - Matched response config for GET /example
22:04:30 DEBUG i.g.i.s.ResponseServiceImpl - Using default HTTP 500 response behaviour for request: GET http://localhost:8888/example
22:04:30 INFO  i.g.i.p.r.RestPluginImpl - Handling GET object request for: http://localhost:8888/example
22:04:30 INFO  i.g.i.s.ResponseServiceImpl - Response file and data are blank - returning empty response for [a36b0a8e-9d3c-42ed-baf8-d56baae04381] GET http://localhost:8888/example
```

Query with baz having value 99 (integer) which should match 2nd rule
```
/ # curl -v -d '{"baz": 99}' -X GET http://localhost:8888/example
*   Trying 127.0.0.1:8888...
* Connected to localhost (127.0.0.1) port 8888 (#0)
> GET /example HTTP/1.1
> Host: localhost:8888
> User-Agent: curl/7.79.1
> Accept: */*
> Content-Length: 11
> Content-Type: application/x-www-form-urlencoded
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< X-Imposter-Request: 922038ea-773c-40f7-a1f9-fcf63647a90d
< Server: imposter
< content-length: 0
<
* Connection #0 to host localhost left intact
```

imposter side (See that it doesn't match response config)
```
22:04:49 DEBUG i.g.i.s.ResponseServiceImpl - Using default HTTP 500 response behaviour for request: GET http://localhost:8888/example
22:04:49 INFO  i.g.i.p.r.RestPluginImpl - Handling GET object request for: http://localhost:8888/example
22:04:49 INFO  i.g.i.s.ResponseServiceImpl - Response file and data are blank - returning empty response for [4514ace6-ddd0-4e11-b867-0a38e756fec5] GET http://localhost:8888/example
```

Query with neither foo nor baz having expected values which should not match any rule but still returns default response from 1st rule. Why is it the default ? It shouldn't match at all
```
/ # curl -v -d '{"no-known-key": "a-value"}' -X GET http://localhost:8888/example
*   Trying 127.0.0.1:8888...
* Connected to localhost (127.0.0.1) port 8888 (#0)
> GET /example HTTP/1.1
> Host: localhost:8888
> User-Agent: curl/7.79.1
> Accept: */*
> Content-Length: 27
> Content-Type: application/x-www-form-urlencoded
>
* Mark bundle as not supporting multiuse
< HTTP/1.1 500 Internal Server Error
< X-Imposter-Request: 6238b636-b576-4900-9f5b-6c2a63c0b67d
< Server: imposter
< content-length: 0
<
* Connection #0 to host localhost left intact
```

imposter side
```
22:06:25 DEBUG i.g.i.s.ResponseServiceImpl - Using default HTTP 500 response behaviour for request: GET http://localhost:8888/example
22:06:25 INFO  i.g.i.p.r.RestPluginImpl - Handling GET object request for: http://localhost:8888/example
22:06:25 INFO  i.g.i.s.ResponseServiceImpl - Response file and data are blank - returning empty response for [6238b636-b576-4900-9f5b-6c2a63c0b67d] GET http://localhost:8888/example
```

**Comment by cscetbon** [comment]
@outofcoffee If I understand this comment it seems that's intended https://github.com/outofcoffee/imposter/blob/382cad03c722cbf2cb2a03dfcda5e26175650bae/core/engine/src/main/java/io/gatehill/imposter/plugin/config/ConfiguredPlugin.kt#L88-L90. But if it is, why ?? It really doesn't make any sense

**Comment by outofcoffee** [comment]
Hi @cscetbon - thank you for the detailed bug report.

At first glance, this looks to be an issue with the precedence logic in `io.gatehill.imposter.http.SingletonResourceMatcher`.

The issue is probably around the `isRequestMatch()` or `filterResourceConfigs()` functions.

I can add your config as a test case to help improve the logic, but for historical/backwards compat reasons, the fallback logic (relating to your query about the default resource being selected) is too optimisic/forgiving about trying to find a match.

To avoid breaking legacy config, something I've been toying with is to add a new 'strict matching' option, which would behave differently and more correctly, frankly, such as:

```
let matched = the resource entries filtered by all those that match on all conditions
if len(matched) == 0
  return 404
else if len(matched) == 1
  return matched[0]
else // len(matched) > 1
  return 4xx? // some error code indicating invalid request
```

WDYT?

**Comment by outofcoffee** [comment]
Imposter has been around for a while, and there are folks who leverage the resource matching behaviour as more of a 'best efforts match, with fallback' rather than an exact match. For better or worse, it was, and is a part of the matching algorithm and changing it will change the semantics for those use cases. In any case, to opt in to strict matching won't be very onerous (either a config file option or environment variable or both), and if it proves to be a positive change, we can make it the default in the next major version.

What are your thoughts on the pseudocode above? Is there anything else you would add?

**Comment by cscetbon** [comment]
> Imposter has been around for a while, and there are folks who leverage the resource matching behaviour as more of a 'best efforts match, with fallback' rather than an exact match. For better or worse, it was, and is a part of the matching algorithm and changing it will change the semantics for those use cases. In any case, to opt in to strict matching won't be very onerous (either a config file option or environment variable or both), and if it proves to be a positive change, we can make it the default in the next major version.

Fair enough

> What are your thoughts on the pseudocode above? Is there anything else you would add?

I'm not sure when that code runs. Is it at the start or whenever there is a request that is received ? Looking at the output log I suppose you got a map of matching conditions -> function
```
14:34:33 DEBUG i.g.i.c.u.ConfigUtil - Loading configuration file: /opt/imposter/config/mock-config.yaml
14:34:41 DEBUG i.g.i.p.r.RestPluginImpl - Adding GET object handler: /
14:34:41 DEBUG i.g.i.p.r.RestPluginImpl - Adding GET object handler: /example
14:34:41 DEBUG i.g.i.p.r.RestPluginImpl - Adding GET object handler: /example
14:34:42 INFO  i.g.i.s.ImposterVerticle - Mock engine up and running on http://localhost:8888
```
And in that case when registering those handlers in the map and if that new parameter is set then I would just exit the program so IMO you wouldn't even have to use your pseudocode. I would prefer at startup to do
```
for handler in config.resources:
  matching_conditions = get_matching_conditions(handler)
  if strict_matching and matching_conditions is in map_handlers:
    raise Exception("2 handlers can't have the same matching conditions when Strict matching is enabled. Fix your configuration")
  map[matching_conditions] = get_function(handler)
```

Does it make sense ?

**Comment by outofcoffee** [comment]
Hi @cscetbon - I had some time to dig into this this weekend.

In your config the HTTP method is set to `GET`, which cannot have an HTTP request body. In the example request, however, you are sending a body:

```
$ curl -v -d '{"baz": "99"}' -X GET http://localhost:8888/example
*   Trying 127.0.0.1:8888...
* Connected to localhost (127.0.0.1) port 8888 (#0)
> GET /example HTTP/1.1
> Host: localhost:8888
> User-Agent: curl/7.79.1
> Accept: */*
> Content-Length: 13
> Content-Type: application/x-www-form-urlencoded
```

This is causing the Vert.x Web library to choke:

```
java.lang.IllegalStateException: Request method must be one of POST, PUT, PATCH or DELETE to decode a multipart request
```

...hence the HTTP 500 response status. I think this may have been mistaken for the 500 status code you defined in your first rule. In fact, the logs show that the 500 is due to the GET/body issue.

If you intended for this to be a `GET` request, rather than, say, a `POST`, then I'm afraid we are constrained by the conventions that the Vert.x Web library supports.

For what it's worth, I switched the `GET` methods in the config to `POST`, and the curl to send a `POST` method, and the behaviour works as you described it should.

---

Modified config:

```yaml
plugin: rest

resources:
- method: POST
  path: /example
  requestBody:
    jsonPath: $.foo
    value: bar
  response:
    statusCode: 500

- method: POST
  path: /example
  requestBody:
    jsonPath: $.baz
    value: 99
  response:
    statusCode: 302
```

Modified curl:
```bash
$ curl -v -d '{"baz": "99"}' -X POST http://localhost:8080/example
Note: Unnecessary use of -X or --request, POST is already inferred.
*   Trying 127.0.0.1:8080...
* Connected to localhost (127.0.0.1) port 8080 (#0)
> POST /example HTTP/1.1
> Host: localhost:8080
> User-Agent: curl/7.79.1
> Accept: */*
> Content-Length: 13
> Content-Type: application/x-www-form-urlencoded
> 
* Mark bundle as not supporting multiuse
< HTTP/1.1 302 Found
< X-Imposter-Request: 74ea1dec-74d1-4168-93e5-f27725cc4cac
< Server: imposter
< content-length: 0
< 
* Connection #0 to host localhost left intact
```
